blank_issues_enabled: false
contact_links:
  - name: PageSpy Website
    url: https://huolalatech.github.io/page-spy-web/
    about: PageSpy introduction.
  - name: Bug Report
    url: https://github.com/HuolalaTech/page-spy-web/issues/new/choose
    about: PageSpy SDK issues should be reported on PageSpy Web Repository.
