on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Send test coverage to coveralls

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install, build, test
        # fake-indexeddb using `structureClone` which import in node^18,
        # and we import the polyfill with `import 'core-js/stable/structured-clone'`
        # to resolve it, so here we pass --ignore-engines after `yarn install` to ignore the error.
        run: |
          yarn install --ignore-engines
          yarn lerna run build
          yarn run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
